repos:
  # Essential hooks only - keep it simple for contributors
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Allow larger files than default

  # Python code formatting - auto-fix, contributor-friendly
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Import sorting - auto-fix
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Basic Python linting - relaxed settings
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        # Only use basic flake8, remove aggressive plugins
        args: [--max-line-length=88, --extend-ignore=E203,W503,E501]

  # Optional: Type checking (can be skipped by contributors)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports, --no-strict-optional, --disable-error-code=misc]

  # Optional: Security scanning (maintainer-focused)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.9
  #   hooks:
  #     - id: bandit
  #       args: [-c, pyproject.toml]

  # Remove strict commit message requirements - too aggressive for contributors
  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v3.2.0
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages: [commit-msg]
  #       args: [optional-scope]
